########################################################
# DO NOT EDIT THIS FILE!
# It is automatically generated from Makefile.src by typing:
#   make -f Makefile.src depend
# 
# Edit Makefile.src, instead.
########################################################
 
########################################################################
#
# eprom_tools: A collection of utilities for use with EPROM programmers
#
# Copyright (C) 1995 Mark J. Blair
#
# This file is part of eprom_tools.
#
#  eprom_tools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  eprom_tools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with eprom_tools.  If not, see <http://www.gnu.org/licenses/>.
# 
########################################################################

CC=gcc
#CFLAGS=-O2
CFLAGS=-g -Wall -Dlint
CTAGS=etags
DEPFLAGS=-E -MM

LIBHEXOBJ=intel.o libhex.o
BINHEXOBJ=bhmain.o
ALLOBJ=$(BINHEXOBJ) $(LIBHEXOBJ) libhex.a
ALLEXE=bin2hex hex2bin
ALLSRC=intel.c libhex.c bhmain.c
ALLHDR=etools.h hex.h

all: $(ALLEXE)

libhex.a: $(LIBHEXOBJ)
	$(AR) $(ARFLAGS) libhex.a $(LIBHEXOBJ)
	ranlib libhex.a

bin2hex: $(BINHEXOBJ) libhex.a
	$(CC) $(CFLAGS) -o bin2hex $(BINHEXOBJ) -L. -lhex

hex2bin: bin2hex
	$(RM) hex2bin
	ln bin2hex hex2bin

depend:
	rm -f Makefile
	@echo '########################################################' \
		> Makefile
	echo '# DO NOT EDIT THIS FILE!' >> Makefile
	@echo '# It is automatically generated from Makefile.src by typing:' \
		>> Makefile
	@echo '#   make -f Makefile.src depend' >> Makefile
	@echo '# ' >> Makefile
	@echo '# Edit Makefile.src, instead.' >> Makefile
	@echo '########################################################' \
		>> Makefile
	@echo ' ' >> Makefile
	cat Makefile.src >> Makefile
	@echo '# The following lines were added by "make depend"' >> Makefile
	$(CC) $(CFLAGS) $(DEPFLAGS) $(ALLSRC) >> Makefile
	chmod ugo-w Makefile

tags: TAGS
TAGS: *.c
	$(CTAGS) *.c

clean:
	$(RM) $(ALLEXE)
	$(RM) $(ALLOBJ)
	$(RM) *~ *.bak TAGS

###
# The following lines were added by "make depend"
intel.o: intel.c etools.h hex.h
libhex.o: libhex.c etools.h hex.h
bhmain.o: bhmain.c etools.h hex.h
